### ISSUE TITLE
`find class…` fails

### ISSUE THREAD

**Issue by seandenigris** [dalehenrich/tode#181]
`tode 1 > find class --full GsNMethod`
returns:
```
Topez ERROR: a TodeCommandError occurred (error 121000), Unknown sub command 'class' for command 'find'
```

**Comment by dalehenrich** [comment]
thanks @seandenigris ... I didn't convert the find command to the new subCommand (welll it was new) structure ... now's a good time ...

**Comment by dalehenrich** [comment]
[clean build](https://travis-ci.org/dalehenrich/tode/builds/74989136)
