### ISSUE TITLE
mention builtIns in shell welcome message ...

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/tode#200]

**Comment by dalehenrich** [comment]
duplicate of #201

**Comment by rjsargent** [comment]
The former is a duplicate of the latter? 
200 vs 201
:-)

<div>-------- Original message --------</div><div>From: Dale Henrichs <notifications@github.com> </div><div>Date:2015/09/16  11:13  (GMT-08:00) </div><div>To: dalehenrich/tode <tode@noreply.github.com> </div><div>Subject: Re: [tode] mention builtIns in shell welcome message ... (#200) </div><div>
</div>duplicate of #201

**Comment by dalehenrich** [comment]
Yeah ... Mariano's was a better bug report:)
