### ISSUE TITLE
Add `builtIns` comment into welcome shell console

### ISSUE THREAD

**Issue by marianopeck** [dalehenrich/tode#201]
@dalehenrich said "the builtIns command (a built-in) lists and describes the built-ins and each built-in has help available via the -h option .... I should probably put this into the banner for the shell console[1]  ...".

I answered:

Yes please!!! I would put a new entry in the welcome:

Welcome to tODE. 
- Enter `help` for information on logging into GemStone. 
- Enter `man gs gemtools` an intro to tODE for GemTools users. 
- Enter `man --all` for information on tODE commands.
- **Enter `builtIns` to list descriptions of built-in commands.**
- Enter `project list` to get busy...

**Comment by dalehenrich** [comment]
will merge to dev ranch soonish
