### ISSUE TITLE
Global shortcut to go to the shell and with cursor in the console

### ISSUE THREAD

**Issue by marianopeck** [dalehenrich/tode#211]
I mean...to give you focus to directly start typing in the console.
This would be useful!

**Comment by dalehenrich** [comment]
@marianopeck do you have a suggestion to use for the shortcut key? `CMD/ALT-SHIFT-T` or  `CMD/ALT-SHIFT-S` or ????

**Comment by marianopeck** [comment]
Hi Dale,

I think that cmd/alt-shift-t will be less confusing that cmd/alt-shift-s
which may be a bit confused when saving (done very frequently).
So I vote for cmd/alt-shift-t.
In think that besides the default what would be super nice is to have that
configurable. So that I can add it to my `go` if I don't like it :)

On Fri, Oct 23, 2015 at 3:07 PM, Dale Henrichs <notifications@github.com>
wrote:

> @marianopeck <https://github.com/marianopeck> do you have a suggestion to
> use for the shortcut key? CMD/ALT-SHIFT-T or CMD/ALT-SHIFT-S or ????
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dalehenrich/tode/issues/211#issuecomment-150650399>.
>



-- 
Mariano
http://marianopeck.wordpress.com

**Comment by dalehenrich** [comment]
... ah, very good point ... I've moved from writing the GsDevKit_home scripts to adding the "tODE essentials" - if I crack open the client-side code, I'll likely add this feature  --- use the "must have" label to mark any other issues that you think need to be addressed before general release in 2 weeks:)

**Comment by marianopeck** [comment]
Thanks Dale. I just checked all the issues I opened, but none of them look
like "must have" from my point of view.
I will keep that in mind if I find further issues.

On Fri, Oct 23, 2015 at 3:24 PM, Dale Henrichs <notifications@github.com>
wrote:

> ... ah, very good point ... I've moved from writing the GsDevKit_home
> scripts to adding the "tODE essentials" - if I crack open the client-side
> code, I'll likely add this feature --- use the "must have" label to mark
> any other issues that you think need to be addressed before general release
> in 2 weeks:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dalehenrich/tode/issues/211#issuecomment-150654611>.
>



-- 
Mariano
http://marianopeck.wordpress.com

**Comment by dalehenrich** [comment]
settled on CMD-SHIFT-G for "got to console"
