### ISSUE TITLE
Add to 'project list' man page the meanings of text decorations

### ISSUE THREAD

**Issue by marianopeck** [dalehenrich/tode#224]
It took me some time to figure out all the meanings of the 'project list' window. Is there a way we could add a "help" command or something that explains what is each? I am still not 100% sure about all of them. Look at the attached screenshot as an example.

| aProject |   ->  project is locked
* aProject    -> the project has been modified in local working copy
+ aProject  -> not sure.. maybe a git fork or branch ?
aProject       -> not sure... maybe BaselineOf or ConfigurationOf is loaded but not the project itself

Anyway..I think we can add this info into the man page of `project list`. For more details see thread with subject "Are the different "notations" of "Projects" windows documented somewhere?"

**Comment by marianopeck** [comment]
Great! Thanks Dale.

**Comment by dalehenrich** [comment]
this will be available with next EA drop
