### ISSUE TITLE
update `test` and `ts` commands to use windows + menu items

### ISSUE THREAD

**Issue by dalehenrich** [dalehenrich/tode#91]
- [x] `test` command
- [x] `ts` command
- [x] test results browser
- [ ] test menu items sprinkled through system

**Comment by pdebruic** [comment]
Would be nice to be able to right click on a subclass of TestCase and choose to run the tests for that class from the menu

**Comment by dalehenrich** [comment]
@pdebruic , how would you like to handle errors and failures? Would you want to open the test browser for the class and launch the tests or something else? The `Debug` menu item runs tests and brings up debugger on first failure ... would that be somethings you'd want?

**Comment by dalehenrich** [comment]
the current behavior is fine....(from Paul)
